import type { UserRow, SecurityEvent, PasswordExpiry } from '../types';

export const MOCK_USERS: UserRow[] = [
  { id: '1', name: 'Ahmed Benali', email: 'ahmed.benali@sti.dz', phone: '+213 555 010 001', employeeId: 'EMP-001', role: 'administrator', region: 'East', wilaya: 'Setif', status: 'online', lastLogin: '2 min ago', lastLoginDate: '2025-07-30T18:00:00', twoFactorEnabled: true, avatar: 'AB', department: 'IT', permissions: [{ module: 'Dashboard', read: true, create: true, update: true, delete: true }, { module: 'Orders', read: true, create: true, update: true, delete: true }, { module: 'Products', read: true, create: true, update: true, delete: true }, { module: 'Clients', read: true, create: true, update: true, delete: true }, { module: 'Reports', read: true, create: true, update: true, delete: true }, { module: 'Settings', read: true, create: true, update: true, delete: true }, { module: 'Users', read: true, create: true, update: true, delete: true }, { module: 'Stock', read: true, create: true, update: true, delete: true }, { module: 'Notifications', read: true, create: true, update: true, delete: true }], loginHistory: [{ id: 'l1', type: 'login', timestamp: '2025-07-30T18:00:00', ipAddress: '192.168.1.100', device: 'Desktop', status: 'success' }, { id: 'l2', type: 'login', timestamp: '2025-07-30T09:15:00', ipAddress: '192.168.1.100', device: 'Desktop', status: 'success' }, { id: 'l3', type: 'password_changed', timestamp: '2025-07-28T14:30:00', ipAddress: '192.168.1.100', device: 'Desktop', status: 'warning' }], devices: [{ type: 'Desktop', browser: 'Chrome 126', ip: '192.168.1.100', location: 'Setif, Algeria', lastActive: '2 min ago' }] },
  { id: '2', name: 'Fatima Zeroual', email: 'fatima.zeroual@sti.dz', phone: '+213 555 010 002', employeeId: 'EMP-002', role: 'administrator', region: 'Center', wilaya: 'Algiers', status: 'online', lastLogin: '5 min ago', lastLoginDate: '2025-07-30T17:55:00', twoFactorEnabled: true, avatar: 'FZ', department: 'Management', permissions: [{ module: 'Dashboard', read: true, create: true, update: true, delete: true }, { module: 'Orders', read: true, create: true, update: true, delete: true }, { module: 'Products', read: true, create: true, update: true, delete: true }, { module: 'Clients', read: true, create: true, update: true, delete: true }, { module: 'Reports', read: true, create: true, update: true, delete: true }, { module: 'Settings', read: true, create: true, update: true, delete: true }, { module: 'Users', read: true, create: true, update: true, delete: true }, { module: 'Stock', read: true, create: true, update: true, delete: true }, { module: 'Notifications', read: true, create: true, update: true, delete: true }], loginHistory: [{ id: 'l4', type: 'login', timestamp: '2025-07-30T17:55:00', ipAddress: '10.0.0.55', device: 'Desktop', status: 'success' }], devices: [{ type: 'Desktop', browser: 'Chrome 126', ip: '10.0.0.55', location: 'Algiers, Algeria', lastActive: '5 min ago' }] },
  { id: '3', name: 'Karim Hadj', email: 'karim.hadj@sti.dz', phone: '+213 555 010 003', employeeId: 'EMP-003', role: 'manager', region: 'West', wilaya: 'Oran', status: 'online', lastLogin: '12 min ago', lastLoginDate: '2025-07-30T17:48:00', twoFactorEnabled: true, avatar: 'KH', department: 'Sales', permissions: [{ module: 'Dashboard', read: true, create: false, update: false, delete: false }, { module: 'Orders', read: true, create: true, update: true, delete: false }, { module: 'Products', read: true, create: true, update: true, delete: false }, { module: 'Clients', read: true, create: true, update: true, delete: false }, { module: 'Reports', read: true, create: false, update: false, delete: false }, { module: 'Stock', read: true, create: true, update: true, delete: false }], loginHistory: [{ id: 'l5', type: 'login', timestamp: '2025-07-30T17:48:00', ipAddress: '172.16.0.22', device: 'Desktop', status: 'success' }], devices: [{ type: 'Desktop', browser: 'Firefox 128', ip: '172.16.0.22', location: 'Oran, Algeria', lastActive: '12 min ago' }] },
  { id: '4', name: 'Amina Bouzid', email: 'amina.bouzid@sti.dz', phone: '+213 555 010 004', employeeId: 'EMP-004', role: 'manager', region: 'East', wilaya: 'Constantine', status: 'online', lastLogin: '18 min ago', lastLoginDate: '2025-07-30T17:42:00', twoFactorEnabled: false, avatar: 'AB', department: 'Operations', permissions: [{ module: 'Dashboard', read: true, create: false, update: false, delete: false }, { module: 'Orders', read: true, create: true, update: true, delete: false }, { module: 'Clients', read: true, create: true, update: true, delete: false }, { module: 'Stock', read: true, create: true, update: true, delete: false }], loginHistory: [{ id: 'l6', type: 'login', timestamp: '2025-07-30T17:42:00', ipAddress: '10.0.1.30', device: 'Mobile', status: 'success' }], devices: [{ type: 'Android', browser: 'Chrome Mobile', ip: '10.0.1.30', location: 'Constantine, Algeria', lastActive: '18 min ago' }] },
  { id: '5', name: 'Omar Tlemcani', email: 'omar.tlemcani@sti.dz', phone: '+213 555 010 005', employeeId: 'EMP-005', role: 'delegate', region: 'West', wilaya: 'Tlemcen', status: 'online', lastLogin: '8 min ago', lastLoginDate: '2025-07-30T17:52:00', twoFactorEnabled: true, avatar: 'OT', department: 'Field Sales', permissions: [{ module: 'Dashboard', read: true, create: false, update: false, delete: false }, { module: 'Orders', read: true, create: true, update: false, delete: false }, { module: 'Clients', read: true, create: true, update: false, delete: false }], loginHistory: [{ id: 'l7', type: 'login', timestamp: '2025-07-30T17:52:00', ipAddress: '192.168.5.10', device: 'Mobile', status: 'success' }], devices: [{ type: 'Android', browser: 'Chrome Mobile', ip: '192.168.5.10', location: 'Tlemcen, Algeria', lastActive: '8 min ago' }] },
  { id: '6', name: 'Yasmine Algiers', email: 'yasmine.algiers@sti.dz', phone: '+213 555 010 006', employeeId: 'EMP-006', role: 'delegate', region: 'Center', wilaya: 'Algiers', status: 'online', lastLogin: '3 min ago', lastLoginDate: '2025-07-30T17:57:00', twoFactorEnabled: false, avatar: 'YA', department: 'Field Sales', permissions: [{ module: 'Dashboard', read: true, create: false, update: false, delete: false }, { module: 'Orders', read: true, create: true, update: false, delete: false }, { module: 'Clients', read: true, create: true, update: false, delete: false }], loginHistory: [{ id: 'l8', type: 'login', timestamp: '2025-07-30T17:57:00', ipAddress: '10.0.2.15', device: 'Mobile', status: 'success' }], devices: [{ type: 'Android', browser: 'Chrome Mobile', ip: '10.0.2.15', location: 'Algiers, Algeria', lastActive: '3 min ago' }] },
  { id: '7', name: 'Rachid Soummam', email: 'rachid.soummam@sti.dz', phone: '+213 555 010 007', employeeId: 'EMP-007', role: 'delegate', region: 'East', wilaya: 'Bejaia', status: 'offline', lastLogin: '3 hours ago', lastLoginDate: '2025-07-30T15:00:00', twoFactorEnabled: true, avatar: 'RS', department: 'Field Sales', permissions: [{ module: 'Dashboard', read: true, create: false, update: false, delete: false }, { module: 'Orders', read: true, create: true, update: false, delete: false }, { module: 'Clients', read: true, create: true, update: false, delete: false }], loginHistory: [{ id: 'l9', type: 'login', timestamp: '2025-07-30T15:00:00', ipAddress: '192.168.3.45', device: 'Desktop', status: 'success' }, { id: 'l10', type: 'logout', timestamp: '2025-07-30T14:30:00', ipAddress: '192.168.3.45', device: 'Desktop', status: 'success' }], devices: [{ type: 'Desktop', browser: 'Chrome 126', ip: '192.168.3.45', location: 'Bejaia, Algeria', lastActive: '3 hours ago' }] },
  { id: '8', name: 'Nadia Charef', email: 'nadia.charef@sti.dz', phone: '+213 555 010 008', employeeId: 'EMP-008', role: 'delegate', region: 'South', wilaya: 'Batna', status: 'online', lastLogin: '1 min ago', lastLoginDate: '2025-07-30T17:59:00', twoFactorEnabled: true, avatar: 'NC', department: 'Field Sales', permissions: [{ module: 'Dashboard', read: true, create: false, update: false, delete: false }, { module: 'Orders', read: true, create: true, update: false, delete: false }, { module: 'Clients', read: true, create: true, update: false, delete: false }], loginHistory: [{ id: 'l11', type: 'login', timestamp: '2025-07-30T17:59:00', ipAddress: '10.0.3.8', device: 'Mobile', status: 'success' }], devices: [{ type: 'Android', browser: 'Chrome Mobile', ip: '10.0.3.8', location: 'Batna, Algeria', lastActive: '1 min ago' }] },
  { id: '9', name: 'Sofiane Merah', email: 'sofiane.merah@sti.dz', phone: '+213 555 010 009', employeeId: 'EMP-009', role: 'delegate', region: 'West', wilaya: 'Oran', status: 'locked', lastLogin: '5 days ago', lastLoginDate: '2025-07-25T10:00:00', twoFactorEnabled: false, avatar: 'SM', department: 'Field Sales', permissions: [{ module: 'Dashboard', read: true, create: false, update: false, delete: false }, { module: 'Orders', read: true, create: true, update: false, delete: false }], loginHistory: [{ id: 'l12', type: 'failed_login', timestamp: '2025-07-25T10:05:00', ipAddress: '192.168.7.20', device: 'Desktop', status: 'danger' }, { id: 'l13', type: 'failed_login', timestamp: '2025-07-25T10:04:00', ipAddress: '192.168.7.20', device: 'Desktop', status: 'danger' }, { id: 'l14', type: 'login', timestamp: '2025-07-25T10:00:00', ipAddress: '192.168.7.20', device: 'Desktop', status: 'success' }], devices: [{ type: 'Desktop', browser: 'Chrome 126', ip: '192.168.7.20', location: 'Oran, Algeria', lastActive: '5 days ago' }] },
  { id: '10', name: 'Yacine Benali', email: 'yacine.benali@sti.dz', phone: '+213 555 010 010', employeeId: 'EMP-010', role: 'delegate', region: 'East', wilaya: 'Setif', status: 'online', lastLogin: '6 min ago', lastLoginDate: '2025-07-30T17:54:00', twoFactorEnabled: true, avatar: 'YB', department: 'Field Sales', permissions: [{ module: 'Dashboard', read: true, create: false, update: false, delete: false }, { module: 'Orders', read: true, create: true, update: false, delete: false }, { module: 'Clients', read: true, create: true, update: false, delete: false }], loginHistory: [{ id: 'l15', type: 'login', timestamp: '2025-07-30T17:54:00', ipAddress: '192.168.1.50', device: 'Mobile', status: 'success' }], devices: [{ type: 'Android', browser: 'Chrome Mobile', ip: '192.168.1.50', location: 'Setif, Algeria', lastActive: '6 min ago' }] },
  { id: '11', name: 'Amine Khelifi', email: 'amine.khelifi@sti.dz', phone: '+213 555 010 011', employeeId: 'EMP-011', role: 'delegate', region: 'Center', wilaya: 'Blida', status: 'online', lastLogin: '10 min ago', lastLoginDate: '2025-07-30T17:50:00', twoFactorEnabled: false, avatar: 'AK', department: 'Field Sales', permissions: [{ module: 'Dashboard', read: true, create: false, update: false, delete: false }, { module: 'Orders', read: true, create: true, update: false, delete: false }], loginHistory: [{ id: 'l16', type: 'login', timestamp: '2025-07-30T17:50:00', ipAddress: '10.0.0.88', device: 'Desktop', status: 'success' }], devices: [{ type: 'Desktop', browser: 'Edge 126', ip: '10.0.0.88', location: 'Blida, Algeria', lastActive: '10 min ago' }] },
  { id: '12', name: 'Mohamed Hakim', email: 'mohamed.hakim@sti.dz', phone: '+213 555 010 012', employeeId: 'EMP-012', role: 'viewer', region: 'Center', wilaya: 'Algiers', status: 'offline', lastLogin: '2 days ago', lastLoginDate: '2025-07-28T16:00:00', twoFactorEnabled: false, avatar: 'MH', department: 'Finance', permissions: [{ module: 'Dashboard', read: true, create: false, update: false, delete: false }, { module: 'Reports', read: true, create: false, update: false, delete: false }], loginHistory: [{ id: 'l17', type: 'login', timestamp: '2025-07-28T16:00:00', ipAddress: '10.0.0.12', device: 'Desktop', status: 'success' }], devices: [{ type: 'Desktop', browser: 'Chrome 126', ip: '10.0.0.12', location: 'Algiers, Algeria', lastActive: '2 days ago' }] },
  { id: '13', name: 'Fatima Ali', email: 'fatima.ali@sti.dz', phone: '+213 555 010 013', employeeId: 'EMP-013', role: 'viewer', region: 'East', wilaya: 'Annaba', status: 'online', lastLogin: '20 min ago', lastLoginDate: '2025-07-30T17:40:00', twoFactorEnabled: true, avatar: 'FA', department: 'HR', permissions: [{ module: 'Dashboard', read: true, create: false, update: false, delete: false }, { module: 'Users', read: true, create: false, update: false, delete: false }], loginHistory: [{ id: 'l18', type: 'login', timestamp: '2025-07-30T17:40:00', ipAddress: '192.168.2.33', device: 'Desktop', status: 'success' }], devices: [{ type: 'Desktop', browser: 'Chrome 126', ip: '192.168.2.33', location: 'Annaba, Algeria', lastActive: '20 min ago' }] },
  { id: '14', name: 'Karim Bouzid', email: 'karim.bouzid@sti.dz', phone: '+213 555 010 014', employeeId: 'EMP-014', role: 'administrator', region: 'West', wilaya: 'Oran', status: 'offline', lastLogin: '1 hour ago', lastLoginDate: '2025-07-30T17:00:00', twoFactorEnabled: true, avatar: 'KB', department: 'IT', permissions: [{ module: 'Dashboard', read: true, create: true, update: true, delete: true }, { module: 'Orders', read: true, create: true, update: true, delete: true }, { module: 'Products', read: true, create: true, update: true, delete: true }, { module: 'Clients', read: true, create: true, update: true, delete: true }, { module: 'Reports', read: true, create: true, update: true, delete: true }, { module: 'Settings', read: true, create: true, update: true, delete: true }, { module: 'Users', read: true, create: true, update: true, delete: true }, { module: 'Stock', read: true, create: true, update: true, delete: true }, { module: 'Notifications', read: true, create: true, update: true, delete: true }], loginHistory: [{ id: 'l19', type: 'login', timestamp: '2025-07-30T17:00:00', ipAddress: '172.16.0.10', device: 'Desktop', status: 'success' }], devices: [{ type: 'Desktop', browser: 'Chrome 126', ip: '172.16.0.10', location: 'Oran, Algeria', lastActive: '1 hour ago' }] },
  { id: '15', name: 'Aicha Djebbar', email: 'aicha.djebbar@sti.dz', phone: '+213 555 010 015', employeeId: 'EMP-015', role: 'delegate', region: 'South', wilaya: 'Ghardaia', status: 'suspended', lastLogin: '14 days ago', lastLoginDate: '2025-07-16T09:00:00', twoFactorEnabled: false, avatar: 'AD', department: 'Field Sales', permissions: [{ module: 'Dashboard', read: true, create: false, update: false, delete: false }], loginHistory: [{ id: 'l20', type: 'login', timestamp: '2025-07-16T09:00:00', ipAddress: '10.0.5.20', device: 'Mobile', status: 'success' }], devices: [{ type: 'Android', browser: 'Chrome Mobile', ip: '10.0.5.20', location: 'Ghardaia, Algeria', lastActive: '14 days ago' }] },
  { id: '16', name: 'Youcef Tlemcani', email: 'youcef.tlemcani@sti.dz', phone: '+213 555 010 016', employeeId: 'EMP-016', role: 'delegate', region: 'West', wilaya: 'Tlemcen', status: 'invited', lastLogin: 'Never', lastLoginDate: '', twoFactorEnabled: false, avatar: 'YT', department: 'Field Sales', permissions: [], loginHistory: [], devices: [] },
];

export const MOCK_SECURITY_EVENTS: SecurityEvent[] = [
  { id: '1', time: '2 min ago', user: 'Ahmed Benali', event: 'Login', ipAddress: '192.168.1.100', device: 'Desktop', status: 'success' },
  { id: '2', time: '5 min ago', user: 'Fatima Zeroual', event: 'Login', ipAddress: '10.0.0.55', device: 'Desktop', status: 'success' },
  { id: '3', time: '12 min ago', user: 'Sofiane Merah', event: 'Failed Login', ipAddress: '192.168.7.20', device: 'Desktop', status: 'danger' },
  { id: '4', time: '18 min ago', user: 'Amina Bouzid', event: 'Password Changed', ipAddress: '10.0.1.30', device: 'Mobile', status: 'warning' },
  { id: '5', time: '25 min ago', user: 'Karim Hadj', event: 'Role Updated', ipAddress: '172.16.0.22', device: 'Desktop', status: 'warning' },
  { id: '6', time: '1 hour ago', user: 'Karim Bouzid', event: 'Login', ipAddress: '172.16.0.10', device: 'Desktop', status: 'success' },
  { id: '7', time: '2 hours ago', user: 'System', event: 'Backup Completed', ipAddress: '10.0.0.1', device: 'Server', status: 'success' },
  { id: '8', time: '3 hours ago', user: 'Rachid Soummam', event: 'Logout', ipAddress: '192.168.3.45', device: 'Desktop', status: 'success' },
];

export const MOCK_PASSWORD_EXPIRY: PasswordExpiry[] = [
  { name: 'Ahmed Benali', daysLeft: 5 },
  { name: 'Karim Bouzid', daysLeft: 9 },
  { name: 'Fatima Ali', daysLeft: 14 },
];

export const ROLE_DISTRIBUTION = [
  { name: 'Administrators', value: 6, color: '#D71920' },
  { name: 'Managers', value: 12, color: '#8B5CF6' },
  { name: 'Delegates', value: 38, color: '#2563EB' },
  { name: 'Viewers', value: 28, color: '#6B7280' },
];

export const SYSTEM_HEALTH = [
  { name: 'API Server', status: 'operational' as const, latency: 18 },
  { name: 'Database', status: 'operational' as const, latency: 12 },
  { name: 'Redis', status: 'operational' as const, latency: 3 },
  { name: 'Socket.IO', status: 'operational' as const, latency: 8 },
  { name: 'Background Jobs', status: 'operational' as const, latency: 24 },
  { name: 'Storage', status: 'operational' as const, latency: 15 },
];
